name: http_toolkit
description: Collection of missing features for the Dart HTTP package.
version: 1.0.0
repository: https://github.com/maranix/http_toolkit
issues: https://github.com/maranix/http_toolkit/issues

topics:
  - network
  - http
  - middleware
  - middlewares
  - interceptors
  - http extensions

environment:
  sdk: ^3.10.1

dependencies:
  http: ^1.2.2

  meta: any
dev_dependencies:
  pedantic_mono: ^1.35.0
  test: ^1.24.0
