name: http_toolkit
description: Collection of missing features for the Dart HTTP package.
version: 2.0.0
homepage: https://github.com/maranix/http_toolkit
repository: https://github.com/maranix/http_toolkit
issues: https://github.com/maranix/http_toolkit/issues

topics:
  - network
  - http
  - middleware
  - interceptor
  - utils

environment:
  sdk: ^3.10.1

dependencies:
  http: ^1.6.0

dev_dependencies:
  pedantic_mono: ^1.35.0
  test: ^1.28.0
